Repository ITU-BDSA2024-GROUP17/Chirp, pull requests merged in 2024-12, with the labels that each got.

#200 Fix ui and max length bug for comments
  src/Chirp.Infrastructure/Repositories/CheepRepository.cs
  src/Chirp.Web/wwwroot/css/index.css
  src/Chirp.Web/wwwroot/js/nav.js
  src/Chirp.Web/wwwroot/js/renders.js
Labels: bug

#238 Add follow test
  test/Chirp.Infrastructure.Tests/Repositories/AuthorRepositoryTests.cs
Labels: test

#257 Upload onion diagram
  docs/diagrams/drawio/ChirpOnionDiagram.drawio
  docs/diagrams/drawio/ChirpOnionDiagram.drawio.xml
  docs/images/ChirpOnionDiagram.drawio-cropped.svg
  docs/images/ChirpOnionDiagram.drawio.svg
  docs/report.md
Labels: documentation, requirement
