Repository ITU-BDSA2024-GROUP17/Chirp, pull requests merged in 2024-10, with the labels that each got.

#93 Feat/search user
  src/SimpleDB/SQLiteDatabase.cs
  src/Web/Interfaces/ICheepService.cs
  src/Web/Pages/Public.cshtml
  src/Web/Pages/Public.cshtml.cs
  src/Web/Pages/Shared/_Layout.cshtml
  src/Web/Pages/UserTimeline.cshtml
  src/Web/Pages/UserTimeline.cshtml.cs
  src/Web/Pages/Util.cs
  src/Web/Services/CheepService.cs
  src/Web/wwwroot/css/index.css
Labels: enhancement

#99 Feat/skip pages
  src/Web/Pages/Public.cshtml
  src/Web/Pages/Shared/_Layout.cshtml
  src/Web/Pages/UserTimeline.cshtml
  src/Web/wwwroot/css/index.css
  src/Web/wwwroot/images/arrow.png
Labels: enhancement

#100 Feat/search
  src/Web/Interfaces/ICheepService.cs
  src/Web/Pages/Public.cshtml
  src/Web/Pages/Public.cshtml.cs
  src/Web/Pages/Search.cshtml
  src/Web/Pages/Search.cshtml.cs
  src/Web/Pages/Shared/_Layout.cshtml
  src/Web/Pages/UserTimeline.cshtml
  src/Web/Pages/_AuthorPartial.cshtml
  src/Web/Pages/_CheepsPartial.cshtml
  src/Web/Services/CheepService.cs
  src/Web/wwwroot/css/index.css
Labels: enhancement

#101 Fix/split search
  src/Web/Interfaces/ICheepService.cs
  src/Web/Pages/Public.cshtml.cs
  src/Web/Pages/Search.cshtml
  src/Web/Pages/Search.cshtml.cs
  src/Web/Pages/Shared/_Layout.cshtml
  src/Web/Pages/_AuthorPartial.cshtml
  src/Web/Pages/_CheepsPartial.cshtml
  src/Web/Services/CheepService.cs
Labels: fix, refactoring

#114 Implemented repository pattern
  src/Web/Interfaces/IAuthorRepository.cs
  src/Web/Interfaces/ICheepRepository.cs
  src/Web/Program.cs
  src/Web/Repositories/AuthorRepository.cs
  src/Web/Repositories/CheepRepository.cs
  src/Web/Services/CheepService.cs
Labels: requirement, refactoring

#116 Feat/1b/extended getters
  src/Chirp.Infrastructure/Services/CheepService.cs
  src/Chirp.Web/Utilities/Util.cs
Labels: enhancement, requirement, refactoring

#117 Add ability to send cheeps
  .gitignore
  src/Chirp.Core/DTOs/cheepDTO.cs
  src/Chirp.Core/Entities/Author.cs
  src/Chirp.Core/Entities/Cheep.cs
  src/Chirp.Core/Interfaces/IAuthorRepository.cs
  src/Chirp.Core/Interfaces/ICheepRepository.cs
  src/Chirp.Infrastructure/Extensions/CheepExtensions.cs
  src/Chirp.Infrastructure/Repositories/AuthorRepository.cs
  src/Chirp.Infrastructure/Repositories/CheepRepository.cs
  src/Chirp.Infrastructure/Services/CheepService.cs
  src/Chirp.Web/Endpoints/CheepEndpoints.cs
  src/Chirp.Web/Pages/Public.cshtml.cs
  src/Chirp.Web/Pages/Shared/_Layout.cshtml
  src/Chirp.Web/Pages/UserTimeline.cshtml.cs
  src/Chirp.Web/Program.cs
  src/Chirp.Web/appsettings.json
  src/Chirp.Web/wwwroot/css/index.css
  test/Chirp.Infrastructure.Tests/Repositories/AuthorRepositoryTests.cs
  test/Chirp.Infrastructure.Tests/Repositories/CheepRepositoryTests.cs
Labels: enhancement, API, UI

#127 1b/Oauth
  .github/workflows/release.yaml
  src/Chirp.Web/Chirp.Web.csproj
  src/Chirp.Web/Program.cs
Labels: requirement

#133 Feat/On-Demand Seach
  src/Chirp.Core/DTOs/authorDTO.cs
  src/Chirp.Web/Endpoints/CheepEndpoints.cs
  src/Chirp.Web/Pages/Public.cshtml
  src/Chirp.Web/Pages/Shared/_Layout.cshtml
  src/Chirp.Web/Pages/_AuthorPartial.cshtml
  src/Chirp.Web/Pages/_CheepsPartial.cshtml
  src/Chirp.Web/Utilities/Util.cs
  src/Chirp.Web/wwwroot/css/index.css
Labels: enhancement, UI
